# Site settings
title: Irisu's Library
description: >- # this means to ignore newlines until "baseurl:"
  Blog of Irisu White
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social account
email: irisu@uprprc.net
github_username:  irisu-white

# Collections
collections:
  RE4B-Challenge:
    output: true

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
mathjax: disabled
sass:
  style: compressed

# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
#gems:
#  - jekyll-feed
#  - jekyll-sitemap
#  - jekyll-seo-tag
